### ISSUE TITLE
About the units of the µ values

### ISSUE THREAD

**Issue by pmunar** [abmantz/cstat#1]
Hi!

First of all, thanks for creating this nice functions from the Kaastra work!

I have, however, a doubt: in the paper the author talks about µ as the expected number of **counts** in each bin. So, I assume the units must be counts (then, for instance, If I have counts/second/keV I have just to multiply each bin by the effective time of observation, right?).

The thing is that I use also Xspec, with the cstat statistic, and the value obtained for C with Xspec and with your code, differ substantially. 
For instance, I tried a model which I know it does not fit the data, which in Xspec gives C-stat = 185 while with your code I obtain C_e = 95 (once summed over all bins)

I do not know where the difference comes from... 

Any ideas?

Thanks!

Pere

**Comment by abmantz** [comment]
Hi there!

I'm sorry not to respond (much) earlier. It appears that I wasn't `Watch`ing this repository, so I had no idea you'd written an issue. Anyway, just in case it's somehow still helpful:

Yes, the Cash statistic only makes sense for data in counts, since it's derived from a Poisson likelihood.

According to the XSPEC manual ([appendix B](https://heasarc.gsfc.nasa.gov/docs/xanadu/xspec/manual/node304.html), eq. B.5) the same formulation of the cstat is used in both codes. Though note that if you're using a Poisson background model through the `backgrnd` command or equivalent, a different formula is used, even though XSPEC still calls the fit statistic by the same name (cstat). Otherwise I'm not sure what to suggest, other than to make absolutely sure that the same set of channels are being used in both calculations, and that kind of thing.
